<a href="https://colab.research.google.com/github/Neil-optimus/python/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [3]:
np.random.seed(42)

In [4]:
raw_sales = np.random.randint(10000, 50000, size=(12, 5)).astype(float)

In [5]:
raw_sales[2, 1] = np.nan
raw_sales[7, 4] = np.nan

In [6]:
traffic = np.random.randint(500, 3000, size=(12, 5))

In [7]:
print(" RAW SALES DATA (with missing values):")
print(raw_sales)

 RAW SALES DATA (with missing values):
[[25795. 10860. 48158. 21284. 16265.]
 [26850. 47194. 31962. 26023. 11685.]
 [10769.    nan 15311. 47819. 49188.]
 [27568. 29769. 38693. 16396. 37480.]
 [35658. 28942. 28431. 12747. 10189.]
 [29118. 45773. 11899. 11267. 41551.]
 [21394. 13556. 13890. 40740. 24502.]
 [31777. 20627. 18792. 18433.    nan]
 [33897. 12612. 33483. 27159. 24541.]
 [45920. 36531. 11585. 13943. 33939.]
 [29457. 11021. 21653. 23417. 19692.]
 [16873. 15675. 10161. 47065. 36557.]]


In [8]:
nan_mask = np.isnan(raw_sales)

In [9]:
valid_sales_mean = np.nanmean(raw_sales)

In [10]:
cleaned_sales = np.copy(raw_sales)
cleaned_sales[nan_mask] = valid_sales_mean

In [11]:
sales_per_customer = cleaned_sales / traffic

In [12]:
taxed_sales = np.copy(cleaned_sales)
taxed_sales[5:8, :] *= 0.95

In [13]:
branch_annual_totals = np.sum(cleaned_sales, axis=0)

In [14]:
monthly_global_totals = np.sum(cleaned_sales, axis=1)
high_performing_months = np.where(monthly_global_totals > 150000)[0]

In [15]:
q4_sales = cleaned_sales[9:12, :]

In [16]:
print("\n" + "="*50 + "\n")
print(f" Imputed {np.sum(nan_mask)} missing values with global mean: ${valid_sales_mean:,.2f}")
print(f" Total Annual Sales by Branch (A to E): {np.array2string(branch_annual_totals, formatter={'float_kind':lambda x: f'${x:,.2f}'})}")
print(f" Months exceeding $150k global sales (0-indexed): {high_performing_months}")
print(f" Average Sales per Customer overall: ${np.mean(sales_per_customer):,.2f}")
print(f" Q4 Total Revenue: ${np.sum(q4_sales):,.2f}")



 Imputed 2 missing values with global mean: $25,923.03
 Total Annual Sales by Branch (A to E): [$335,076.00 $298,483.03 $284,018.00 $306,293.00 $331,512.03]
 Months exceeding $150k global sales (0-indexed): []
 Average Sales per Customer overall: $18.31
 Q4 Total Revenue: $373,489.00
